
@startuml activity2
title "Atualizar quantidade do item";
start
:Atualizar quantidade do item;
if (nova quantidade <= 0) then (sim)
  : remover item (pelo ISBN);
  stop
else (não)
  : procurar item do carrinho pelo ISBN do livro;
  if (livro encontrado) then (sim)
    : verificar estoque do livro;
    if (estoque do livro >= nova quantidade) then (sim)
      : atualizar quantidade do item com a nova quantidade;
      : "Quantidade de <nome do livro> atualizado para <nova quantidade>";
      : salvar carrinho;
    else (não)
      : "Estoque insuficiente para <nome do livro>. Disponível: <estoque do livro>";
    endif
  else (não)
    : "Item com ISBN <ISBN> não encontrado no carrinho";
  endif
endif
stop
@enduml